### ISSUE TITLE
When do you think this will be finished?

### ISSUE THREAD

**Issue by YoungPup** [Paulowarren31/Supreme-Bot#1]
When do you think this will be finished?

**Comment by Paulowarren31** [comment]
It is basically complete, just not tested very much. I will use it on the next drop and try to test it on the Japan site before the NA drop.

**Comment by limsammy** [comment]
@Paulowarren31 How did it work with the drop yesterday?

**Comment by Nexus154** [comment]
Also wondering how the last drop went for you.

**Comment by Paulowarren31** [comment]
Today I tried it and got a black overdyed sweatshirt in small. Last week i got a joe roberts swirl tee.

**Comment by Nexus154** [comment]
I also tested and it worked but you can only get one item at a time. Trying to list multiple items didn't work for me.

**Comment by Paulowarren31** [comment]
There was a bug with multiple items that I (hopefully) fixed. The latest working version is on the chrome store, you can update by removing the extension and adding it again.

Also make sure that you list the codes separated by only commas (Gwm1jejzwdk,Xsugtetlwy0,Ivlvvzg2kei,7s7sx71mbr8)

**Comment by Nexus154** [comment]
Yes I downloaded from chrome store and separated only by commas (no spaces). Maybe the problem came in with sizes? Let's say we want different sizes for each item... will the bot support that? I'm pretty sure I had it listed just like your example on the chrome store.  E.g. Lets say I have item1,item2,item3. Sizing would be large(item1),medium(item2),small(item3) correct?

**Comment by Paulowarren31** [comment]
The sizing is based on priority, so if you gave the sizes Large,Medium,Small it would try and get Large in each of the items, and if they were unavailable it would try to get the next sizes.

**Comment by Nexus154** [comment]
Just tested again and for some reason it still adds only one item to cart. Tested using the following items. 
![screen shot 2017-03-02 at 10 00 01 pm](https://cloud.githubusercontent.com/assets/26100583/23536550/aac5f7e4-ff93-11e6-934a-e61298ab492a.png)
![screen shot 2017-03-02 at 10 00 16 pm](https://cloud.githubusercontent.com/assets/26100583/23536555/ad2cd192-ff93-11e6-8496-acf8c2d83e44.png)
![screen shot 2017-03-02 at 9 58 43 pm](https://cloud.githubusercontent.com/assets/26100583/23536521/7a9447b0-ff93-11e6-8149-05e3e470bd91.png)
For some reason it only adds the last item and it carted the medium even though I listed large first.

**Comment by Paulowarren31** [comment]
Ah this was a bug where it wouldn't find items with spaces, and skips over
the items after that one. I fixed this and is now in the updated version of
the extension.

**Comment by barolow** [comment]
I appreciate your really nice work.
Please let me know what should I put setting non-sized items(like backpack), newera size(like 7 5/8) and shoes size (like 10.5)?

**Comment by Paulowarren31** [comment]
non sized items should be detected by the bot and added if available. For all other sizes, Make sure you include the same exact text as shown in the size select. So for shoes/pants it should be like 36,9.5 etc. I have not tested with shoes as there arent any on the store right now, but it should still work.
