### ISSUE TITLE
How do I find item codes, and how do I launch this

### ISSUE THREAD

**Issue by ollie-thomas** [Paulowarren31/Supreme-Bot#2]

**Comment by ollie-thomas** [comment]
Sorry I'm fairly new to this scene

**Comment by Paulowarren31** [comment]
No worries.

To find item codes, they are found by going to the japanese Supreme online store the night before to check. 

 It's a chrome extension so after you clone the repo you can go to chrome extensions and click load unpacked extension, and select the folder you just cloned.

**Comment by ollie-thomas** [comment]
Ah so i get the code of the url to the item on the japanese store?

**Comment by Paulowarren31** [comment]
It's actually something you find in the html of the store/all page. If you go to the store and inspect element on an image of a n item, it should have an "alt" attribute. That's what we are looking for.

**Comment by ollie-thomas** [comment]
Okay thanks a lot, so to access the japanese supreme website i just need to use supremenewyork.jp?

**Comment by ollie-thomas** [comment]
And also I'm in the UK, can I adapt this to work?

**Comment by Paulowarren31** [comment]
I just put the extension up on the store https://chrome.google.com/webstore/detail/ez-preme/pifcojpimhgdcegdfohnmjmbpiiphghi

**Comment by limsammy** [comment]
Where exactly do we input the item we're after and our billing/shipping info?
