### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by lodlum** [Paulowarren31/Supreme-Bot#49]
Testing it out with incorrect payment information, I added the Akira/Supreme ceramic white plate. When I active the bot it takes me to the plate but then it doesn't go to basket, once I click basket it autofills the information but doesn't do anything else

**Comment by lodlum** [comment]
Also I noticed on many items the bot doesn't take me to the actual item, just constantly refreshes

**Comment by Paulowarren31** [comment]
This is a problem with the image codes not being consistent between the UK
and US stores. The codes I pull from the UK aren't guaranteed to match the
items. In this case it is unfortunate but the bot is unable to find the
ceramic white plate.
